apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: evershop
  name: evershop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evershop
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: evershop
    spec:
      containers:
      - image: benjaminmelki/evershop-test:latest
        name: evershop
        env:
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_USER
          value: "postgres"
        - name: DB_NAME
          value: "postgres"
        ports:
        - containerPort: 3000
#        resources:
#          requests:
#            cpu: 400m
#            memory: 700Mi
#          limits:
#            cpu: 500m
#            memory: 800Mi
        volumeMounts:
        - name: evershop-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: evershop-persistent-storage
        persistentVolumeClaim:
          claimName: evershop-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evershop-pv-claim
  labels:
    app: evershop
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
