name: Build and deploy an app to AKS

on:
#  push:
  workflow_dispatch:

env:
    image-order: ${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest
    image-product: ${{ secrets.DOCKERHUB_USERNAME }}/product-service:latest
    image-front: ${{ secrets.DOCKERHUB_USERNAME }}/store-front:latest
    nomcluster: nomcluster
    nom-grouperessource: grouperessource
    platforms: linux/amd64
    location: francecentral
    sensible-pas-afficher: 1>/dev/null

permissions:
  pull-requests: read

jobs:
  buildproductservice:
    runs-on: ubuntu-latest
    steps:
      - name: checkout  
        uses: actions/checkout@v4

      - name: Login to docker Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push test
        uses: docker/build-push-action@v5
        with:    
          tags: |
            ${{ env.image-product }}
          context: ./product-service
          platforms: ${{ env.platforms }}
          push: true
      
  buildorderservice:
    runs-on: ubuntu-latest
    steps:
    - name: checkout  
      uses: actions/checkout@v4  

    - name: Login to docker Container Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push test
      uses: docker/build-push-action@v5
      with:    
        tags: |
          ${{ env.image-order }}
        context: ./order-service
        platforms: ${{ env.platforms }}
        push: true

  buildstore-front:
    runs-on: ubuntu-latest
    steps:
    - name: checkout  
      uses: actions/checkout@v4

    - name: Login to docker Container Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push test
      uses: docker/build-push-action@v5
      with:    
        tags: |
          ${{ env.image-front }}
        context: ./store-front
        platforms: ${{ env.platforms }}
        push: true
  
  createcluster:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: Azure/login@v2.0.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: create groupe Azure
        run: az group create --name ${{ env.nom-grouperessource }} --location ${{ env.location }} ${{ env.sensible-pas-afficher }}

      - name: creation cluster aks
        run: |
          az resource --exists --name "${{ env.nomcluster }}" --resource-group "${{ env.nom-grouperessource }}" --resource-type "Microsoft.ContainerService/managedClusters" || az aks create --resource-group ${{ env.nom-grouperessource }} --name ${{ env.nomcluster }} --enable-managed-identity --node-count 1 --generate-ssh-keys --enable-cluster-autoscaler --min-count 1 --max-count 2 --location ${{ env.location }} ${{ env.sensible-pas-afficher }} --node-vm-size Standard_B2s

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: checkout   
        uses: actions/checkout@v4

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.3.0
        env:
          verif: git diff --name-only ${{ github.sha }} | grep prduct-service | grep store-front| grep order-service
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        with:
          args:
            -Dsonar.projectKey=MelkiBenjamin_test-sonarqube
            -Dsonar.organization=melkibenjamin
            -Dsonar.sources=. 
            -Dsonar.qualitygate.wait=true
            #-Dsonar.verbose=true 
          projectBaseDir: .

  monitoring:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: [createcluster, sonarcloud]
    steps:
      - name: Azure login
        uses: Azure/login@v2.0.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get K8s context
        uses: Azure/aks-set-context@v4.0.0
        with:
          resource-group: ${{ env.nom-grouperessource }}
          cluster-name: ${{ env.nomcluster }}

      - name: setup kubectl
        uses: Azure/setup-kubectl@v4.0.0
        id: install

      - name: install helm
        uses: Azure/setup-helm@v4
        id: install-helm

      - name: install helm apli monitoring
        run: |
          kubectl get namespace monitoring || kubectl create namespace monitoring
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm upgrade --install my-kube-prometheus-stack prometheus-community/kube-prometheus-stack --version 57.0.3 -n monitoring --atomic --wait

#      - name: redirection de port
#        run: |
#          echo '{"spec": {"type": "LoadBalancer"}}' > patch.json
#          kubectl patch svc my-kube-prometheus-stack-grafana --type merge --patch "$(cat patch.json)" -n monitoring

  argocd:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: [createcluster, sonarcloud]
    steps:
       
      - name: Azure login
        uses: Azure/login@v2.0.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get K8s context
        uses: Azure/aks-set-context@v4.0.0
        with:
          resource-group: ${{ env.nom-grouperessource }}
          cluster-name: ${{ env.nomcluster }}

      - name: setup kubectl   
        uses: Azure/setup-kubectl@v4.0.0      
        id: install
        
      - name: Setup ArgoCD CLI 
        uses: imajeetyadav/argocd-cli@v1

      - name: create namespace argocd
        run: kubectl get namespace argocd || kubectl create namespace argocd

      - name: Deploys application argocd
        uses: Azure/k8s-deploy@v5.0.0
        with:
          namespace: argocd
          action: deploy
          manifests: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

      - name: attendre argocd
        run: |
          kubectl wait --for=condition=available deployment --all -n argocd
          sleep 60

      - name: load balancing
        run: |
          echo '{"spec": {"type": "LoadBalancer"}}' > patch.json
          kubectl patch svc argocd-server -n argocd --type merge --patch "$(cat patch.json)"
              
      - name: connexion argocd 1er connexion
#        env:
#          ip: kubectl get svc argocd-server -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
#          mdp: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo
        run: argocd login $(kubectl get service argocd-server -n argocd --output=jsonpath='{.status.loadBalancer.ingress[0].ip}') --username admin --password $(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo) --insecure ${{ env.sensible-pas-afficher }}

      - name: update ArgoCD password
#        env:
#          ARGOCD: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo
#          mdp: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo
        run: argocd account update-password --account admin --new-password ${{ secrets.ARGOCD }} --current-password $(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo) ${{ env.sensible-pas-afficher }}

  contoso:
    runs-on: ubuntu-latest
    needs: [argocd, buildproductservice, buildorderservice, buildstore-front]
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: Azure login
        uses: Azure/login@v2.0.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get K8s context
        uses: Azure/aks-set-context@v4.0.0
        with:
          resource-group: ${{ env.nom-grouperessource }}
          cluster-name: ${{ env.nomcluster }}

      - name: setup kubectl   
        uses: Azure/setup-kubectl@v4.0.0      
        id: install
      
      - name: Setup ArgoCD CLI 
        uses: imajeetyadav/argocd-cli@v1

      - name: connexion argocd
        env:
          ip: kubectl get svc argocd-server -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
          mdp: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo
        run: argocd login $(kubectl get service argocd-server -n argocd --output=jsonpath='{.status.loadBalancer.ingress[0].ip}') --username admin --password ${{ secrets.ARGOCD }} --insecure ${{ env.sensible-pas-afficher }}

      - name: Create Application Contoso with Argocd avec namespace
        run: |
          kubectl get namespace contoso || kubectl create namespace contoso
          
      - name: Create Application Contoso with Argocd avec namespace
        uses: clowdhaus/argo-cd-action/@v2.2.0
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 2.11.3
          command: app
          options: create contoso --repo https://github.com/MelkiBenjamin/deploiement-apli-kubernetes-argocd --path ecommerce --dest-server https://kubernetes.default.svc --dest-namespace contoso --sync-policy automated --auto-prune
  
