name: Build aplication

on:
  push:
  workflow_dispatch:

jobs:
  buildproductservice:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build image docker
        run: |
          cd product-service
          docker build -t product-service .
        
      - name: images docker
        run: docker images

      - name: Login to docker Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push test
        uses: docker/build-push-action@v5
        with:    
          context: ./product-service
          platforms: linux/amd64
          push: true
      
  buildorderservice:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  
    
    - name: docker build
      run: |
        cd order-service
        docker build -t order-service .

  buildstore-front:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: build image docker
      run: |
        cd store-front
        docker build -t store-front .
