name: Build aplication

on:
  push:
  workflow_dispatch:

env:
    image: ${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest

jobs:
  buildproductservice:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build image docker
        run: |
          cd product-service
          docker build -t product-service .
        
      - name: images docker
        run: docker images
      
  buildorderservice:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  
    
    - name: docker build
      run: |
        cd order-service
        docker build -t order-service .

    - name: Login to docker Container Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push test
      uses: docker/build-push-action@v5
      with:    
        tags: |
          ${{ env.image }}
        context: ./product-service
        platforms: linux/amd64
        push: true

  buildstore-front:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: build image docker
      run: |
        cd store-front
        docker build -t store-front .
