name: Build aplication

on:
  push:
  workflow_dispatch:

env:
    image1: ${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest
    image2: ${{ secrets.DOCKERHUB_USERNAME }}/product-service:latest
    image3: ${{ secrets.DOCKERHUB_USERNAME }}/store-front:latest

jobs:
  buildproductservice:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to docker Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push test
        uses: docker/build-push-action@v5
        with:    
          tags: |
            ${{ env.image2 }}
          context: ./product-service
          platforms: linux/amd64
          push: true
      
  buildorderservice:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  

    - name: Login to docker Container Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push test
      uses: docker/build-push-action@v5
      with:    
        tags: |
          ${{ env.image1 }}
        context: ./order-service
        platforms: linux/amd64
        push: true

  buildstore-front:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to docker Container Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push test
      uses: docker/build-push-action@v5
      with:    
        tags: |
          ${{ env.image3 }}
        context: ./store-front
        platforms: linux/amd64
        push: true
