name: test contoso

on:
  push:
  workflow_dispatch:

env:
    image-order: ${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest
    image-product: ${{ secrets.DOCKERHUB_USERNAME }}/product-service:latest
    image-front: ${{ secrets.DOCKERHUB_USERNAME }}/store-front:latest
    nomcluster: nomcluster
    nom-grouperessource: grouperessource
    platforms: linux/amd64
    location: francecentral
    sensible-pas-afficher: 1>/dev/null

permissions:
  pull-requests: read

jobs:
  contoso:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: Azure/login@v2.0.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get K8s context test
        uses: Azure/aks-set-context@v4.0.0
        with:
          resource-group: ${{ env.nom-grouperessource }}
          cluster-name: ${{ env.nomcluster }}

      - name: setup kubectl   
        uses: Azure/setup-kubectl@v4.0.0      
        id: install

      - name: Setup ArgoCD CLI 
        uses: imajeetyadav/argocd-cli@v1

      - name: connexion argocd
        env:
          ip: kubectl get svc argocd-server -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
          mdp: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo
        run: argocd login $(kubectl get service argocd-server -n argocd --output=jsonpath='{.status.loadBalancer.ingress[0].ip}') --username admin --password ${{ secrets.ARGOCD }} --insecure ${{ env.sensible-pas-afficher }}

      - uses: clowdhaus/argo-cd-action/@v2.2.0
        env:
        # Only required for first step in job where API is called
        # All subsequent setps in a job will not re-download the CLI
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 2.11.3
          command: app
          options: create contoso --repo https://github.com/MelkiBenjamin/deploiement-apli-kubernetes-argocd --path ecommerce --dest-server https://kubernetes.default.svc --dest-namespace contoso --sync-policy automated --auto-prune

