name: test contoso

on:
  push:
  workflow_dispatch:

env:
    image-order: ${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest
    image-product: ${{ secrets.DOCKERHUB_USERNAME }}/product-service:latest
    image-front: ${{ secrets.DOCKERHUB_USERNAME }}/store-front:latest
    nomcluster: nomcluster
    nom-grouperessource: grouperessource
    platforms: linux/amd64
    location: francecentral
    sensible-pas-afficher: 1>/dev/null

permissions:
  pull-requests: read

jobs:
  contoso:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: Azure/login@v2.0.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get K8s context
        uses: Azure/aks-set-context@v4.0.0
        with:
          resource-group: ${{ env.nom-grouperessource }}
          cluster-name: ${{ env.nomcluster }}

      - name: setup kubectl   
        uses: Azure/setup-kubectl@v4.0.0      
        id: install
      
      - name: Setup ArgoCD CLI 
        uses: imajeetyadav/argocd-cli@v1

      - name: connexion argocd
        env:
          ip: kubectl get svc argocd-server -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
          mdp: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo
        run: argocd login $(kubectl get service argocd-server -n argocd --output=jsonpath='{.status.loadBalancer.ingress[0].ip}') --username admin --password ${{ secrets.ARGOCD }} --insecure ${{ env.sensible-pas-afficher }}

#      - name: Create Application Contoso with Argocd avec namespace
#        run: |
#          kubectl create namespace contoso
#          kubectl config set-context --current --namespace=argocd
#          kubectl apply -f https://raw.githubusercontent.com/MelkiBenjamin/deploiement-apli-kubernetes-argocd/main/ecommerce/values1.yaml
#          kubectl apply -f https://raw.githubusercontent.com/MelkiBenjamin/deploiement-apli-kubernetes-argocd/main/ecommerce/values2.yaml
#          argocd app create ecommerce --repo https://github.com/MelkiBenjamin/deploiement-apli-kubernetes-argocd --path ecommerce --dest-server https://kubernetes.default.svc --dest-namespace contoso --sync-policy automated --auto-prune

      - uses: ejhayes/action-argocd-deploy@releases/v1
        with:
            clientId: admin
            clientSecret: ${{ secrets.ARGOCD }}
            clusterName: 'default'
            baseUrl: https://localhost.com
            name: my-service
            namespace: contoso
            path: ecommerce
            project: ecommerce
            valuesFile: ecommerce/values1.yaml, ecommerce/values2.yaml
            annotations: |
              myannotation: "true"
            labels: |
              group: group-a
              env: prod
            info: |
              rev: ${{ github.ref }}
              sha: ${{ github.sha }}