name: sonarqube verification

on:
#  push:
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
#    container:
#        image: mcr.microsoft.com/azure-cli:latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v4

      - name: install cli az
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      # Logs in with your Azure credentials
      - name: Azure login
        uses: Azure/login@v2.0.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: conexion au cluster
        run: az aks get-credentials --resource-group monResourceGroup --name monClusterAKS

      - uses: Azure/setup-kubectl@v4.0.0
        id: install

      - name : port-forward
        run: kubectl port-forward svc/sonarqube-sonarqube -n sonarqube --address 0.0.0.0 9000 &

#      - name: Wait for SonarQube to be ready
#        run: sleep 60

#      - name: curl sonarqube
#        run: |
#          apk add curl

#      - name: ping sonarqube
#        run: |
#          ping -c 5 127.0.0.1:9000

#      - name : kubectl get svc -n sonarqube
#        run: kubectl get svc -n sonarqube

      - name: download cli sonarqube et lancer sonarqube
        run: |
          curl https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip --output sonar-scanner-cli-5.0.1.3006-linux.zip

      - name: ls
        run: ls          
      - name: unzip cli sonarqube
        run: unzip sonar-scanner-cli-5.0.1.3006-linux.zip

#      - name: lance sonarqube
#        run: |
#          sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner -Dsonar.projectKey=sonarqube -Dsonar.sources=. -Dsonar.host.url=${{ secrets.SONAR_IP }} -Dsonar.login=${{ secrets.SONAR_LOGIN }} -Dsonar.password=${{ secrets.SONAR_PASSWORD }}

      - name: Official SonarQube Scan test
        uses: SonarSource/sonarqube-scan-action@v2.0.1
        env:
        #  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_IP }}
        with:
            projectBaseDir: .
            args: >
              -Dsonar.login=${{ secrets.SONAR_LOGIN }}
              -Dsonar.password=${{ secrets.SONAR_PASSWORD }}
              -Dsonar.projectKey=sonarqube
              -Dsonar.sources=.
    #      sonar.login: admin
    #      sonar.password: admin
    #      sonar.projectKey: sonarqube
    #      sonar.sources: .
