name: suprime le cluster azure
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  nomcluster: nomcluster
  nom-grouperessource: grouperessource

jobs:
  clusterdestoy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: Azure/login@v2.0.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Suppression du cluster
        if: kubectl get clusterrolebinding | grep -q ${{ env.nomcluster }} && kubectl get group
        run: az aks delete --resource-group ${{ env.nom-grouperessource }} --name ${{ env.nomcluster }} --yes