name: suprime le cluster azure
on:
#  push:
  workflow_dispatch:

env:
  nomcluster: nomcluster
  nom-grouperessource: grouperessource

jobs:
  clusterdestoy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # Logs in with your Azure credentials
      - name: Azure login
        uses: Azure/login@v2.0.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Suppression du cluster
        run: az aks delete --resource-group ${{ env.nom-grouperessource }} --name ${{ env.nomcluster }} --yes --no-wait