name: suprime le cluster azure
on:
  push:
  workflow_dispatch:

jobs:
  clusterdestoy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # Logs in with your Azure credentials
      - name: Azure login
        uses: Azure/login@v2.0.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

#      - name: conexion au cluster
#        run: az aks get-credentials --resource-group monResourceGroup --name monClusterAKS
      
      - name: Suppression du cluster
        run: az aks delete --resource-group monResourceGroup --name monClusterAKS --yes --no-wait